# Use postgres/example user/password credentials
version: '3.8'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: JOptionPane
      POSTGRES_USER: root
      POSTGRES_DB: tesis
      POSGRES_HOST: localhost
    ports:
      - 5432:5432
    

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 81:80
    depends_on:
      - db
    