create table if not exists plants(
    id integer primary key generated by default as identity,
    scientific_name varchar (100) UNIQUE,
    name varchar (50),
    descripcion text

);

create table if not exists images(
    id integer primary key generated by default as identity,
    url text not null check (url <> ''),
    plantId integer references plant(id)
)